name: Publish Packages

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: dotnet3.1
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: dotnet3.1
    - name: Publish Hydra.Core.Abstractions
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: dotnet3.1/Framework/Hydra.Core.Abstractions/Hydra.Core.Abstractions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: Hydra.Core.Abstractions
          NUGET_SOURCE: https://api.nuget.org
          VERSION_SUFIX: stage-2
